import type { JudgeProvider } from "../../domain/ai/judge-provider";
import type { RequirementAnalysis, RequirementInput } from "../../schemas/analysis";
import type { QAReview } from "../../schemas/review";
import { qaReviewSchema } from "../../schemas/review";

const JUDGE_JSON_SCHEMA = {
  type: "object",
  properties: {
    score: { type: "integer" },
    overallAssessment: { type: "string" },
    strengths: { type: "array", items: { type: "string" } },
    issues: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: { type: "string" },
          type: {
            type: "string",
            enum: [
              "MISSING_SCENARIO",
              "INVALID_SCENARIO",
              "WEAK_EXPECTED_RESULT",
              "MISSING_PRECONDITION",
              "MISSING_TEST_DATA",
              "GHERKIN_ERROR",
              "INVENTED_RULE",
              "CONTRADICTION",
              "INSUFFICIENT_COVERAGE",
              "REDUNDANT_TEST",
            ],
          },
          severity: { type: "string", enum: ["LOW", "MEDIUM", "HIGH", "CRITICAL"] },
          description: { type: "string" },
          affectedTestCase: { type: "string" },
          recommendedAction: { type: "string" },
        },
        required: ["id", "type", "severity", "description", "recommendedAction"],
      },
    },
    missingScenarios: { type: "array", items: { type: "string" } },
    potentiallyInventedRules: { type: "array", items: { type: "string" } },
    gherkinIssues: { type: "array", items: { type: "string" } },
    coverageAssessment: { type: "string" },
    recommendations: { type: "array", items: { type: "string" } },
  },
  required: [
    "score",
    "overallAssessment",
    "strengths",
    "issues",
    "missingScenarios",
    "potentiallyInventedRules",
    "gherkinIssues",
    "coverageAssessment",
    "recommendations",
  ],
};

export class GeminiQAJudge implements JudgeProvider {
  readonly name = "gemini-judge";
  private readonly apiKey: string;
  private readonly model: string;

  constructor(apiKey: string, model: string = "gemini-3.6-flash") {
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is not defined.");
    }
    this.apiKey = apiKey;
    this.model = model;
  }

  async reviewAnalysis(input: RequirementInput, analysis: RequirementAnalysis): Promise<QAReview> {
    const isPt = input.locale === "pt";

    const systemPrompt = `You are a Principal QA Architect and Lead Reviewer. Your task is to critically evaluate a QA Analysis generated by another AI against the Original Requirement.
You MUST output your response in JSON format conforming strictly to the provided JSON Schema.
All text values in the JSON MUST be written in ${isPt ? "Portuguese" : "English"}.

GOLDEN RULE: The current requirement is primary; confirmed project rules are complementary context. If they conflict, report POTENTIAL_REQUIREMENT_CONFLICT; do not silently choose either.
- Identify if the Analysis invented business rules, limits, timeouts, or constraints not present in the requirement.
- Ensure the Analysis correctly identified ambiguities and missing information instead of assuming them.
- Review coverage systematically, not by counting scenarios. First identify every explicitly described behavior in the Original Requirement: flows, rules, fields, states, conditions, dependencies, integrations, actors, and permissions. Then compare each behavior against the Test Cases and coverageSummary.
- Report INSUFFICIENT_COVERAGE when one or more relevant explicit behaviors are not covered, even if the analysis has many Test Cases. Conversely, do not demand scenarios for dimensions that are not applicable to the requirement.
- Verify applicable happy paths, alternatives, validations, negative cases, boundaries, state changes, integrations, authorization, persistence, error recovery, edge cases, and regression only when supported by the requirement.
- For each behavior that cannot have an objective expected outcome because the requirement omits information, require it in coverageSummary.uncoveredAreas and as a gap/ambiguity; never request an invented rule.
- Verify totalTestCases equals the actual Test Case count and that the summary category counts match the scenarios' stated purpose.
- Do NOT alter the original analysis. You are reviewing it and pointing out flaws or strengths.
- Score the analysis from 0 to 100 based on accuracy, completeness, and adherence to the original requirement (no hallucinations).
- Be critical. Do not inflate the score. A corrected analysis should still be scored independently — never add points just because a correction step ran.

FIELDS TO POPULATE:
- 'score': 0-100 rating of the analysis quality. Penalize hallucinations heavily.
- 'overallAssessment': Summary of the review.
- 'strengths': What the analysis did well (e.g., good test cases, correctly spotted gaps).
- 'issues': Detailed array of specific issues found in the analysis. For each issue, provide a unique 'id' (e.g., 'ISSUE-001'), classify its 'type' and 'severity', describe the problem in 'description', identify the 'affectedTestCase' ID (if applicable, else omit), and provide a 'recommendedAction'.
- 'missingScenarios': Specific missing behaviors/scenarios based on the requirement. State the explicit rule, flow, field, state, or dependency that needs coverage; do not use generic requests such as "add more tests".
- 'potentiallyInventedRules': Rules, limits, or data that the analysis assumed but are NOT in the requirement. Be extremely strict here.
- 'gherkinIssues': Flaws in the Gherkin scenarios (e.g., poorly written, testing invented rules).
- 'coverageAssessment': Explain which explicit behaviors are covered, which are missing, and which are correctly listed as uncovered due to insufficient requirement information.
- 'recommendations': Actionable steps to improve the QA approach for this requirement.`;

    const userPrompt = `ORIGINAL REQUIREMENT DETAILS:
Locale: ${input.locale}
User Story: ${input.userStory || "Not provided"}
Requirement: ${input.requirement}
Acceptance Criteria: ${input.acceptanceCriteria || "Not provided"}
Additional Context: ${input.additionalContext || "Not provided"}
Relevant Project Context (with provenance): ${input.projectContext?.promptContext || "Not provided"}

GENERATED QA ANALYSIS TO REVIEW:
${JSON.stringify(analysis, null, 2)}`;

    const url = `https://generativelanguage.googleapis.com/v1beta/models/${this.model}:generateContent?key=${this.apiKey}`;

    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        systemInstruction: {
          parts: [{ text: systemPrompt }],
        },
        contents: [
          {
            parts: [{ text: userPrompt }],
          },
        ],
        generationConfig: {
          responseMimeType: "application/json",
          responseSchema: JUDGE_JSON_SCHEMA,
        },
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        throw new Error(`Gemini Judge API error: Rate limit exceeded (Status 429).`);
      }
      throw new Error(`Gemini Judge API error: Request failed with status ${response.status}.`);
    }

    const data = await response.json();
    const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text) {
      throw new Error("Invalid response structure from Gemini Judge API.");
    }

    try {
      const parsed = JSON.parse(text);
      return qaReviewSchema.parse(parsed) as QAReview;
    } catch (e) {
      if (e instanceof SyntaxError) {
        throw new Error("Failed to parse Gemini Judge response as JSON.");
      }
      throw e;
    }
  }
}
