import type { RequirementAnalysis } from "../schemas/analysis";

export type ExportableAnalysis = { id: string; requirement: string; additionalContext?: string | null; userStory?: string | null; createdAt: Date | string; project?: { name: string } | null; result: RequirementAnalysis };
const list = (items: string[]) => items.length ? items.map((item) => `- ${item}`).join("\n") : "- Not available";
const section = (title: string, value: string) => `## ${title}\n\n${value}\n`;
const escapePdf = (value: string) => value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)").replace(/[^\x20-\x7E]/g, "?");

export function buildAnalysisMarkdown(record: ExportableAnalysis): string {
  const a = record.result;
  const sources = a.contextSourcesUsed ?? [];
  const impact = a.regressionImpact ?? { impactedModules: [], relatedRules: [], relatedFeatures: [], recommendedRegressionScenarios: [], potentialRequirementConflicts: [] };
  const sourceRows = sources.length ? sources.map((source) => `- ${source.type}: ${source.title} (${source.source})`).join("\n") : "- No persisted project context was used.";
  const testCases = a.scenarios.map((scenario) => `### ${scenario.id} - ${scenario.title}\n\n- **Type:** ${scenario.type}\n- **Priority:** ${scenario.priority}\n- **Description:** ${scenario.description}\n\n#### Preconditions\n\n${list(scenario.prerequisites)}\n\n#### Test Data\n\n${scenario.testData || "Not available"}\n\n#### Steps\n\n${scenario.steps.map((step, index) => `${index + 1}. ${step}`).join("\n")}\n\n#### Expected Result\n\n${scenario.expectedBehavior}\n\n#### Gherkin\n\n\`\`\`gherkin\n${scenario.gherkin}\n\`\`\``).join("\n\n");
  return `# ${a.summary || "QAVeil Analysis"}\n\n_Exported ${new Date(record.createdAt).toISOString()}_\n\n${section("Requirement", record.requirement)}${section("Additional Context", record.additionalContext || "Not provided")}${record.project ? section("Project", record.project.name) : ""}${section("Context Sources Used", sourceRows)}${section("Requirement Analysis", `### Summary\n\n${a.summary}\n\n### Actors\n\n${list(a.actors)}\n\n### Business Rules\n\n${list(a.businessRules)}\n\n### Dependencies\n\n${list(a.dependencies)}\n\n### Preconditions\n\n${list(a.preconditions)}\n\n### Postconditions\n\n${list(a.postconditions)}\n\n### Ambiguities\n\n${a.ambiguities.length ? a.ambiguities.map((x) => `- **${x.term}:** ${x.problem} Question: ${x.questionForPo}`).join("\n") : "- None"}\n\n### Missing Information\n\n${list(a.missingInformation)}\n\n### Questions for PO\n\n${list(a.questionsForPo)}`)}${section("Risk Analysis", `- **Risk Score:** ${a.risk.score}\n- **Risk Level:** ${a.risk.level}\n- **Rationale:** ${a.risk.rationale}\n\n### Factors\n\n${list(a.risk.factors)}`)}${section("Regression Impact", `### Impacted Modules\n\n${list(impact.impactedModules)}\n\n### Related Rules\n\n${list(impact.relatedRules)}\n\n### Related Features / Integrations\n\n${list(impact.relatedFeatures)}\n\n### Recommended Regression\n\n${list(impact.recommendedRegressionScenarios)}`)}${section("Coverage", `- **Total Test Cases:** ${a.coverageSummary.totalTestCases}\n- **Happy Path:** ${a.coverageSummary.happyPathCases}\n- **Negative:** ${a.coverageSummary.negativeCases}\n- **Edge:** ${a.coverageSummary.edgeCases}\n- **Uncovered Areas:**\n${list(a.coverageSummary.uncoveredAreas)}`)}## Test Cases\n\n${testCases}\n`;
}

export function buildAnalysisPdf(record: ExportableAnalysis): Uint8Array {
  const lines = buildAnalysisMarkdown(record).replace(/```[\s\S]*?```/g, "Gherkin included in Markdown export.").split("\n").flatMap((line) => line.match(/.{1,88}(?:\s|$)|\S+?(?:\s|$)/g) ?? [""]);
  const pages: string[][] = []; for (let index = 0; index < lines.length; index += 44) pages.push(lines.slice(index, index + 44));
  const objects: string[] = ["<< /Type /Catalog /Pages 2 0 R >>", `<< /Type /Pages /Kids [${pages.map((_, i) => `${3 + i * 2} 0 R`).join(" ")}] /Count ${pages.length} >>`];
  pages.forEach((page, i) => { const stream = ["BT", "/F1 10 Tf", "50 790 Td", ...page.flatMap((line, lineIndex) => [`(${escapePdf(line)}) Tj`, ...(lineIndex < page.length - 1 ? ["0 -16 Td"] : [])]), "ET"].join("\n"); objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 ${3 + pages.length * 2} 0 R >> >> /Contents ${4 + i * 2} 0 R >>`, `<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`); });
  objects.push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"); let pdf = "%PDF-1.4\n"; const offsets = [0]; objects.forEach((object, i) => { offsets.push(Buffer.byteLength(pdf)); pdf += `${i + 1} 0 obj\n${object}\nendobj\n`; }); const xref = Buffer.byteLength(pdf); pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, "0")} 00000 n \n`).join("")}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return new TextEncoder().encode(pdf);
}
