import type { RequirementAnalysis } from "../schemas/analysis";
export type CoverageStatus = "COVERED" | "PARTIALLY_COVERED" | "NOT_COVERED";
export type TraceabilityItem = { id: string; type: "REQUIREMENT" | "BUSINESS_RULE"; text: string; source: "CURRENT_REQUIREMENT" | "PROJECT_CONTEXT"; sourceTitle?: string; coveredBy: string[]; status: CoverageStatus; playwrightStatus: "PLAYWRIGHT_GENERATED" | "NOT_GENERATED" };
export type TraceabilityMatrix = { items: TraceabilityItem[]; metrics: { total: number; covered: number; partial: number; notCovered: number; percentage: number }; uncoveredItems: TraceabilityItem[] };
const words = (value: string) => [...new Set((value.toLowerCase().match(/[\p{L}\p{N}]{4,}/gu) ?? []).filter((word) => !["para", "como", "when", "that", "with", "system", "sistema"].includes(word)))];
const conservativelyMatches = (item: string, scenario: RequirementAnalysis["scenarios"][number]) => { const tokens = words(item); const scenarioText = words([scenario.title, scenario.description, scenario.expectedBehavior, ...scenario.steps, scenario.gherkin].join(" ")); return tokens.length > 1 && tokens.filter((token) => scenarioText.includes(token)).length >= 2; };
export function buildTraceabilityMatrix(analysis: RequirementAnalysis, generatedTestCaseIds: readonly string[] = []): TraceabilityMatrix {
  const sourceForRule = (rule: string) => { const source = (analysis.contextSourcesUsed ?? []).find((entry) => entry.type === "BUSINESS_RULE" && (rule.includes(entry.title) || entry.title.includes(rule))); return source ? { source: "PROJECT_CONTEXT" as const, sourceTitle: source.title } : { source: "CURRENT_REQUIREMENT" as const }; };
  const candidates = [ ...analysis.requirementFacts.map((text, index) => ({ id: `REQ-${String(index + 1).padStart(3, "0")}`, type: "REQUIREMENT" as const, text, source: "CURRENT_REQUIREMENT" as const })), ...analysis.businessRules.map((text, index) => ({ id: `BR-${String(index + 1).padStart(3, "0")}`, type: "BUSINESS_RULE" as const, text, ...sourceForRule(text) })) ];
  const items = candidates.map((item) => { const coveredBy = analysis.scenarios.filter((scenario) => { const behaviors = scenario.coveredBehaviorIds ?? [], rules = scenario.coveredBusinessRuleIds ?? []; return (item.type === "REQUIREMENT" ? behaviors : rules).includes(item.id) || ((!behaviors.length && !rules.length) && conservativelyMatches(item.text, scenario)); }).map((scenario) => scenario.id); const partial = coveredBy.length > 0 && analysis.coverageSummary.uncoveredAreas.some((area) => words(item.text).some((word) => words(area).includes(word))); return { ...item, coveredBy, status: coveredBy.length ? partial ? "PARTIALLY_COVERED" as const : "COVERED" as const : "NOT_COVERED" as const, playwrightStatus: coveredBy.some((id) => generatedTestCaseIds.includes(id)) ? "PLAYWRIGHT_GENERATED" as const : "NOT_GENERATED" as const }; });
  const covered = items.filter((item) => item.status === "COVERED").length, partial = items.filter((item) => item.status === "PARTIALLY_COVERED").length, notCovered = items.length - covered - partial;
  return { items, metrics: { total: items.length, covered, partial, notCovered, percentage: items.length ? Math.round(((covered + partial * .5) / items.length) * 100) : 0 }, uncoveredItems: items.filter((item) => item.status === "NOT_COVERED") };
}
